[package]
name = "iban"
description = "IBAN parsing library"
license = "MIT OR Apache-2.0"
repository = "https://github.com/JohnPeel/iban"
documentation = "https://docs.rs/iban"
version = "0.0.1"
edition = "2021"

[dependencies]
