permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: test

jobs:
  required:
    runs-on: ubuntu-latest
    name: required / ${{ matrix.toolchain }}
    strategy:
      matrix:
        toolchain: [stable, beta]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - if: hashFiles('Cargo.lock') == ''
        run: cargo generate-lockfile
      - run: cargo test --locked --all-features --all-targets
      - run: cargo test --locked --all-features --doc
  minimal:
    runs-on: ubuntu-latest
    name: minimal-versions / stable
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@stable
      - uses: dtolnay/rust-toolchain@nightly
      - run: rustup default stable
      - run: cargo +nightly update -Zdirect-minimal-versions
      - run: cargo test --locked --all-features --all-targets
  os-check:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} / stable
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@stable
      - if: hashFiles('Cargo.lock') == ''
        run: cargo generate-lockfile
      - run: cargo test --locked --all-features --all-targets
  coverage:
    runs-on: ubuntu-latest
    name: coverage / stable
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo clean
      - run: cargo test --all-features --no-fail-fast --tests
        env:
          CARGO_INCREMENTAL: "0"
          RUSTFLAGS: "-Cinstrument-coverage -Ccodegen-units=1"
          RUSTDOCFLAGS: "-Cinstrument-coverage -Ccodegen-units=1"
          LLVM_PROFILE_FILE: "target/coverage/raw/cargo-test-%p-%m.profraw"
      - run: grcov target/coverage/raw --binary-path target/debug/deps -s . -t lcov --branch --ignore-not-existing --ignore '../*' --ignore '/*' -o target/coverage/lcov.info
      # TODO: target/coverage/lcov.info => GitHub?
